name: 'MongoDB query evaluator'
description: 'MongoDB query evaluator action for Tryber projects'
inputs:
  db_restore_dir:
    description: 'GitHub repository directory that contains the dataset collections to be restored.'
    default: 'assets'
    required: true
  challenges_dir:
    description: 'GitHub repository directory that contains the student MQL scripts.'
    default: 'challenges'
    required: true
  pr_author_username:
    description: 'Pull Request author username.'
    required: true
outputs:
  result:
    description: 'Evaluation JSON results in base64 format.'
runs:
  using: 'docker'
  image: 'Dockerfile'
