name: 'MongoDB query evaluator'
description: 'MongoDB query evaluator action for Tryber projects'
inputs:
  repository-import-folder:
    description: 'GitHub repository folder that contains the BSONs.'
    default: 'assets'
    required: true
  repository-challenges-folder:
    description: 'GitHub repository folder that contains the MQL scripts.'
    default: 'challenges'
    required: true
outputs:
  result:
    description: 'Evaluation JSON results in base64 format.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository-import-folder }}
    - ${{ inputs.repository-challenges-folder }}
